
[theme]
# Primary accent color for interactive elements.
primaryColor = "#d00000"

# Background color for the main content area.
backgroundColor = "#003566"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#107E7D"

# Color used for almost all text.
textColor = "#fff"